name: Weekly Data Extraction

on:
  schedule:
    # Every Monday at 2 AM UTC (8 PM Sunday EST)
    - cron: '0 2 * * MON'
  
  # Allow manual runs for testing
  workflow_dispatch:

jobs:
  extract-data:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Service Fusion extraction
      run: python project_dashboard_ytd.py
      env:
        SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
        SF_CLIENT_SECRET: ${{ secrets.SF_CLIENT_SECRET }}
        DATE_RANGE: "Year to Date"
        
    - name: Run Kimai extraction  
      run: python kimai_extraction.py
      env:
        KIMAI_API_TOKEN: ${{ secrets.KIMAI_API_TOKEN }}
        KIMAI_BASE_URL: ${{ secrets.KIMAI_BASE_URL }}
    
    - name: List generated files
      run: |
        echo "Files created:"
        ls -la *.xlsx *.csv *.log 2>/dev/null || echo "No files found"
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: weekly-data-${{ github.run_number }}
        path: |
          *.xlsx
          *.csv
          *.log
        retention-days: 90
    
    - name: Log completion
      run: |
        echo "Weekly extraction completed at $(date)"
        echo "Check artifacts for generated files"
